services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3042:3042"
